version: '3.9'
services:
  app_db:
    image: mysql:8.0.31
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      # - MYSQL_USER=albertoapi
      # - MYSQL_PASSWORD=alberto
    volumes:
      - mysql_database:/var/lib/mysql
  alberto_api:
    depends_on:
      - app_db
    build: ./api_rest/
    # restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=app_db
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    # ports:
    #   - "3000:3000"
    # links:
    #   - app_db
volumes:
  mysql_database:
