version: '3.9'
services:
  dietario_db:
    build: ./db/
    env_file: ./.env
    restart: unless-stopped
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      # - MYSQL_USER=$MYSQLDB_USER
      # - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
    volumes:
      - mysql_database:/var/lib/mysql
  backend:
    depends_on:
      - dietario_db
    build: ./api_rest/
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=dietario_db
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
  frontend:
    build: ./front-dietario/
    env_file:
      - ./.env
    ports:
      - $VUE_LOCAL_PORT:$VUE_DOCKER_PORT
    environment:
      - PORT=$NODE_DOCKER_PORT
      - DOMAIN=backend
volumes:
  mysql_database:
